# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kusion < Formula
  desc "Codify and deliver intentions to Kubernetes and Clouds"
  homepage "https://github.com/healthjyk/kusion"
  version "1.0.9"
  license "Apache License"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/healthjyk/kusion/releases/download/v1.0.9/kusion_1.0.9_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "990ab6c2458f48bcfc879942922fd773b70cf79b0eaf34b855c6bc3a59139edd"

      def install
        bin.install "kusion"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/healthjyk/kusion/releases/download/v1.0.9/kusion_1.0.9_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "ca7d4ae71fd2c976c59bede85719a01f0268d2a06fc1de48310d6b1f70c8eb7f"

      def install
        bin.install "kusion"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/healthjyk/kusion/releases/download/v1.0.9/kusion_1.0.9_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "3f5b359ef597921db50f228fa892feb5a7ebef7d2b0a44ba5435a290f5c10c70"

      def install
        bin.install "kusion"
      end
    end
  end
end
